---
- name: Check whether vim is installed
  ansible.builtin.command: vim --version
  register: vim_installed
  changed_when: false
  ignore_errors: true

- name: Install Vim enhanced
  ansible.builtin.package:
    name: vim-enhanced
    state: present
  when: vim_installed is failed

- name: Change vim command to vi
  ansible.builtin.lineinfile:
    dest: /etc/profile
    line: alias vi='vim'
    state: present
  when: vim_installed is failed

- name: "Create the .vimrc file under {{ vimrc_dir }}"
  ansible.builtin.template:
    src: .vimrc
    dest: "{{ vimrc_dir }}/.vimrc"
    group: "{{ vimrc_group }}"
    owner: "{{ vimrc_owner }}"
    mode: "{{ vimrc_mode }}"
  when: vim_installed is failed
