---
- name: Check whether vim is installed
  command: vim --version
  register: VIM_INSTALLED
  changed_when: false
  ignore_errors: true

- name: Install Vim enhanced with yum
  package:
    name: vim-enhanced
    state: present
  when: VIM_INSTALLED is failed

- name: Change vim command to vi
  lineinfile:
    dest: /etc/profile
    line: alias vi='vim'
    state: present
  when: VIM_INSTALLED is failed

- name: Create .vimrc
  become: false
  template:
    src: .vimrc
    dest: "{{ vimrc_dir }}/.vimrc"
  when: VIM_INSTALLED is failed
