---
- name: Install Vim enhanced with yum
  yum:
    name: vim-enhanced
    state: present

- name: Change vim command to vi
  lineinfile:
    dest: /etc/profile
    line: alias vi='vim'
    state: present

- name: Create .vimrc
  become: false
  template:
    src: .vimrc
    dest: "{{ vimrc_dir }}/.vimrc"
