---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether vim is installed
      ansible.builtin.command: vim --version
      register: vim_version
      changed_when: false
      ignore_errors: true

    - name: Check whether .vimrc is created with appropriate permissions and owner
      ansible.builtin.command: ls -al /home/vimtest/
      register: vimrc_info
      changed_when: false
      ignore_errors: true

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure vim is installed
      ansible.builtin.debug:
        var: vim_version

    - name: Make sure .vimrc is created with appropriate permissions and owner
      ansible.builtin.debug:
        var: vimrc_info

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
