---
name: ansible-playbook
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade Ansible
        run: |
          pip install --upgrade ansible==2.9.9

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker run CentOS7 image sudo installed
        run: |
          docker run -d -t --name=mycontainer \
          tomonorimatsumura/ansible-test:latest

      - name: Install Ansible galaxy roles
        run: |
          ansible-galaxy install -r tests/roles/requirements.yml -p tests/roles

      - name: Execute ansible-playbook command
        run: |
          ansible-playbook -i 'mycontainer,' -c docker -u ansible \
          -e vimrc_dir='/home/ansible' tests/test.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Check idempotency
        run: |
          ansible-playbook -i 'mycontainer,' -c docker -u ansible \
          -e vimrc_dir='/home/ansible' tests/test.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Check if the command works
        run: |
          docker exec --tty mycontainer env TERM=xterm vim --version

      - name: Show Ansible version
        run: |
          ansible --version

      - name: Show OS information
        run: |
          docker exec --tty mycontainer env TERM=xterm cat /etc/redhat-release
